DEMO_SCAN = {
    "overall_score": 78,
    "nodes": [
        {"node_type": "domain", "label": "democollege.edu", "ip": "192.168.1.10", "severity": "low", "raw_data": {}},
        {"node_type": "subdomain", "label": "portal.democollege.edu", "severity": "medium", "raw_data": {}},
        {"node_type": "subdomain", "label": "admin.democollege.edu", "severity": "medium", "raw_data": {}},
        {"node_type": "subdomain", "label": "mail.democollege.edu", "severity": "low", "raw_data": {}},
        {"node_type": "subdomain", "label": "vpn.democollege.edu", "severity": "low", "raw_data": {}},
        {"node_type": "subdomain", "label": "library.democollege.edu", "severity": "low", "raw_data": {}},
        {"node_type": "port", "label": "democollege.edu:22", "ip": "192.168.1.10", "port": 22, "severity": "high", "raw_data": {}},
        {"node_type": "port", "label": "democollege.edu:80", "ip": "192.168.1.10", "port": 80, "severity": "medium", "raw_data": {}},
        {"node_type": "port", "label": "democollege.edu:443", "ip": "192.168.1.10", "port": 443, "severity": "low", "raw_data": {}},
        {"node_type": "port", "label": "democollege.edu:3306", "ip": "192.168.1.10", "port": 3306, "severity": "critical", "raw_data": {}},
        {"node_type": "breach", "label": "Breach: democollege.edu", "severity": "critical", "raw_data": {"breaches": ["Collection1", "LinkedIn2021"]}},
        {"node_type": "ssl_issue", "label": "SSL Issue: democollege.edu", "severity": "high", "raw_data": {"ssl_error": "Certificate expired 15 days ago"}},
        {"node_type": "ssl_issue", "label": "Missing SPF: democollege.edu", "severity": "medium", "raw_data": {"issue": "No SPF record — email can be spoofed"}},
        {"node_type": "ssl_issue", "label": "Missing DMARC: democollege.edu", "severity": "high", "raw_data": {"issue": "No DMARC record — no email authentication"}},
    ],
    "edges": [
        {"source_label": "democollege.edu", "target_label": "portal.democollege.edu", "relationship_type": "has_subdomain"},
        {"source_label": "democollege.edu", "target_label": "admin.democollege.edu", "relationship_type": "has_subdomain"},
        {"source_label": "democollege.edu", "target_label": "mail.democollege.edu", "relationship_type": "has_subdomain"},
        {"source_label": "democollege.edu", "target_label": "vpn.democollege.edu", "relationship_type": "has_subdomain"},
        {"source_label": "democollege.edu", "target_label": "library.democollege.edu", "relationship_type": "has_subdomain"},
        {"source_label": "democollege.edu", "target_label": "democollege.edu:22", "relationship_type": "has_port"},
        {"source_label": "democollege.edu", "target_label": "democollege.edu:80", "relationship_type": "has_port"},
        {"source_label": "democollege.edu", "target_label": "democollege.edu:443", "relationship_type": "has_port"},
        {"source_label": "democollege.edu", "target_label": "democollege.edu:3306", "relationship_type": "has_port"},
        {"source_label": "democollege.edu", "target_label": "Breach: democollege.edu", "relationship_type": "has_breach"},
        {"source_label": "democollege.edu", "target_label": "SSL Issue: democollege.edu", "relationship_type": "has_ssl_issue"},
        {"source_label": "democollege.edu", "target_label": "Missing SPF: democollege.edu", "relationship_type": "has_ssl_issue"},
        {"source_label": "democollege.edu", "target_label": "Missing DMARC: democollege.edu", "relationship_type": "has_ssl_issue"},
    ],
    "chains": [
        {
            "rule_id": "RULE_01",
            "severity": "critical",
            "title": "Remote Credential Attack",
            "explanation": "SSH is open and credentials have appeared in data breaches. Attackers can attempt credential stuffing against SSH.",
            "node_ids": [],
        },
        {
            "rule_id": "RULE_02",
            "severity": "high",
            "title": "Multiple Exposed Admin Interfaces",
            "explanation": "Found 2 admin-related subdomains: portal and admin. Each is a potential entry point for attackers.",
            "node_ids": [],
        },
        {
            "rule_id": "RULE_03",
            "severity": "high",
            "title": "Invalid SSL Certificate",
            "explanation": "SSL certificate for democollege.edu is expired. This enables man-in-the-middle attacks.",
            "node_ids": [],
        },
        {
            "rule_id": "RULE_05",
            "severity": "critical",
            "title": "MySQL Port Exposed",
            "explanation": "MySQL (port 3306) is exposed to the internet. Database ports should never be publicly accessible.",
            "node_ids": [],
        },
        {
            "rule_id": "RULE_09",
            "severity": "medium",
            "title": "Large Attack Surface (5 subdomains)",
            "explanation": "Found 5 subdomains. Each represents a potential entry point.",
            "node_ids": [],
        },
        {
            "rule_id": "RULE_12",
            "severity": "medium",
            "title": "Missing SPF Record",
            "explanation": "No SPF record found for democollege.edu. Anyone can spoof email from this domain.",
            "node_ids": [],
        },
        {
            "rule_id": "RULE_13",
            "severity": "high",
            "title": "Missing DMARC Policy",
            "explanation": "No DMARC record found for democollege.edu. This is the #1 defense against CEO fraud and business email compromise.",
            "node_ids": [],
        },
    ],
}
